//
//  Model.swift
//  SwiftUICollectionView
//
//  Created by Adrian B. Haeske on 14.02.21.
//

import Foundation

struct Vegetable: Hashable {
    let id = UUID()
    var name: String
    var color: String

    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }

    static func == (lhs: Vegetable, rhs: Vegetable) -> Bool {
        lhs.id == rhs.id
    }

    static let preview = Vegetable(name: "Cucumber", color: "green")

    static let exampleItems = [
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown"),
        Vegetable(name: "Asparagus", color: "white"),
        Vegetable(name: "Carrot", color: "orange"),
        Vegetable(name: "Broccoli", color: "green"),
        Vegetable(name: "Ginger", color: "brown")
    ]

}
